### ISSUE TITLE
💡 [REQUEST] - TTP Integration Tests

### ISSUE THREAD

**Issue by l50** [facebookincubator/TTPForge#346]
### Summary

We need to be able to speak to the working state of a given TTP in ForgeArmory. To do this, we should create a github action that will run the various TTPs in Armory against a target. This will give us some degree of certainty that a given TTP is "working as expected."

### Basic Example

I'd really just throw the proposed github action code in here, so I'm not sure what example I can provide at this time.

### Drawbacks

- Adds overhead to maintain the actions

**Comment by d3sch41n** [comment]
I will implement integration tests specifically for a chosen set of example TTPs, as other armory contents will have lots of dependencies that can't be reproduced in a test environment. 

There may be some headaches with the proposed approach, as it is placing code and its associated tests in different repos. This is unusual and has some pitfalls:

* Making an atomic update (as a single PR) to both code and its associated tests is not possible. This complicates situations where you need to change both the code and the test 
* We  can't use the example TTPs as embedded code snippets in this repo - so basically all the actual usage docs have to live in armory, which is a little weird because we need one repo where the docs outline the overall vision of the tool, which should probably be this one because internal customers don't currently use the armory.  

I think this just life with the project split into two repos though, there may not be a good solution. 

This is worth a shot - I'll give it a try. If things don't work out, I might explore moving the examples into this repository.

**Comment by d3sch41n** [comment]
Covered by integration testing in:

https://github.com/facebookincubator/TTPForge/pull/446
https://github.com/facebookincubator/TTPForge/pull/448

Other parts of armory may be covered as desired using internal test config
